spring:
  application:
    name: elasticsearch-application

#  elasticsearch:
#    rest:
#      uris: -101.43.19.137:9300

  data:
    mongodb:
      host: 127.0.0.1
      database: articledb
      port: 27017

system:
  elasticsearch:
    hosts: -101.43.19.137:9200  # 多个结点用逗号分隔

