spring:
  application:
    name: boot-demo-application

  datasource:
    url: jdbc:mysql://localhost:3306/data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #  elasticsearch:
#    rest:
#      uris: -101.43.19.137:9300

#  data:
#    mongodb:
#      host: 127.0.0.1
#      database: articledb
#      port: 27017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

system:
  elasticsearch:
    hosts: -101.43.19.137:9200  # 多个结点用逗号分隔

