server:
  port: 8081

spring:
  application:
    name: redis-demo-application

  data:
    redis:
      repositories:
        enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 20
        min-idle: 10