server:
  port: 8081

spring:
  application:
    name: boot-demo-application

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

system:
  elasticsearch:
    hosts: localhost:9200  # 多个结点用逗号分隔