server:
  port: 8081

spring:
  application:
    name: boot-demo-application

    elasticsearch:
      rest:
        uris: -127.0.0.1:9300

system:
  elasticsearch:
    hosts: localhost:9200  # 多个结点用逗号分隔